---
abstract: 'Version Control for Translation'
author:
  - 'Ktat, C<< <ktat at cpan.org> >>'
  - 'Ktat <ktat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tran
no_index:
  directory:
    - inc
    - t
recommends:
  Cvs::Simple: 0
  Email::MIME: 0
  Email::Sender::Simple: 0
  Git::Class: 0
  Net::Twitter: 0
requires:
  App::Cmd: 0
  Archive::Tar: 0
  Class::Inspector: 0
  Clone: 0
  Cwd: 0
  Data::Visitor: 0
  File::Copy: 0
  File::Find: 0
  File::Path: 0
  File::Slurp: 0
  FindBin: 0
  IO::Prompt: 0
  IO::String: 0
  IO::Uncompress::Bunzip2: 0
  IO::Uncompress::Gunzip: 0
  LWP::Simple: 0
  Module::Build: 0
  Module::Pluggable: 0
  Storable: 0
  Text::Diff: 0
  Text::Diff3: 0
  Util::Any: 0.17
  YAML::XS: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
